export const sportIcons: Record<string, string> = {
  hiking: '🥾',
  trekking: '🎒',
  canoe: '🚣',
  'ski-touring': '⛷',
  'trail-running': '🏃',
  mountaineering: '🏔',
  cycling: '🚴',
  kayaking: '🛶',
  surfing: '🏄',
  sailing: '⛵',
  paragliding: '🪂',
  skiing: '⛷',
  snowboarding: '🏂',
  running: '🏃',
  swimming: '🏊',
  football: '⚽',
  tennis: '🎾',
  volleyball: '🏐',
  badminton: '🏸',
  canyoning: '🌊',
  diving: '🤿',
  'stand-up-paddle': '🏄',
  rafting: '🚣',
  'ice-climbing': '🧊',
  'cross-country-ski': '🎿',
  skateboarding: '🛹',
  skydiving: '🪂',
  crossfit: '🏋️',
  'rock-fishing': '🎣',
  'horseback-riding': '🏇',
  'via-ferrata': '⛓',
  // Sports expansion (mig 00276)
  'climbing-sport': '🧗',
  'climbing-multipitch': '🧗',
  bouldering: '🪨',
  'dry-tooling': '🪓',
  caving: '🕳️',
  snowshoeing: '🌨',
  'ski-freeride': '🎿',
  splitboard: '🏂',
  'mtb-xc': '🚵',
  'mtb-enduro': '🚵',
  'mtb-downhill': '🚵',
  gravel: '🚲',
  'speed-riding': '🪂',
  'hang-gliding': '🛩',
  freediving: '🤿',
};

export function getSportIcon(sportKey: string): string {
  return sportIcons[sportKey] ?? '🏅';
}
