export const sportIcons: Record<string, string> = {
  hiking: '🥾',
  climbing: '🧗',
  'ski-touring': '⛷',
  'trail-running': '🏃',
  mountaineering: '🏔',
  cycling: '🚴',
  'mountain-biking': '🚵',
  kayaking: '🛶',
  surfing: '🏄',
  sailing: '⛵',
  paragliding: '🪂',
  skiing: '⛷',
  snowboarding: '🏂',
  running: '🏃',
  swimming: '🏊',
  football: '⚽',
  tennis: '🎾',
  volleyball: '🏐',
  badminton: '🏸',
  canyoning: '🌊',
  diving: '🤿',
  'stand-up-paddle': '🏄',
  rafting: '🚣',
  'ice-climbing': '🧊',
  'cross-country-ski': '🎿',
  skateboarding: '🛹',
  skydiving: '🪂',
  triathlon: '🏅',
  crossfit: '🏋️',
  'rock-fishing': '🎣',
  'horseback-riding': '🏇',
  'via-ferrata': '⛓',
  slacklining: '🤸',
};

export function getSportIcon(sportKey: string): string {
  return sportIcons[sportKey] ?? '🏅';
}
