-- ============================================================================
-- 00440 — Demo profile Hugo P.: level overestimated on trail AND running
-- (Scott 2026-10-05). 00439 gave him 5 « surestimé » on trail but 00438 had
-- also given him 5 « juste » there, so the honesty triangle read balanced;
-- and he had no running outing at all (a level vote is attached to the
-- sport of an outing). This: drops his « juste » votes on trail, adds one
-- completed running outing where he is present (Marie's footing along the
-- Durance), and seeds « surestimé » from its 4 present co-participants.
-- Reliability stays « Faible » (present 5 / absent 6 / 1 late withdrawal →
-- 46); Léa is marked absent on it so she stays « Correcte » (70). Generated by the same formula-simulating script as 00438/00439.
-- ============================================================================
DELETE FROM reputation_votes
WHERE voted_id = 'd0000000-0000-4000-a000-000000000008' AND badge_key = 'level_right';

INSERT INTO activities
  (id, creator_id, sport_id, title, description, level, level_max,
   max_participants, location_meeting, meeting_name,
   location_objective, objective_name,
   starts_at, duration, visibility, requires_presence, status,
   distance_km, elevation_gain_m, is_demo)
VALUES
  ('c0000000-0000-4000-a000-000000000027', 'd0000000-0000-4000-a000-000000000002',
   (SELECT id FROM sports WHERE key = 'running'),
   'Footing au bord de la Durance', 'Dix kilomètres plats le long de la Durance, allure tranquille.',
   'intermédiaire', NULL, 8,
   ST_SetSRID(ST_MakePoint(6.635, 44.895), 4326)::geography, 'Briançon gare',
   ST_SetSRID(ST_MakePoint(6.6, 44.87), 4326)::geography, 'Pont de Prelles',
   now() - INTERVAL '55 days', INTERVAL '2 hours', 'public', true, 'completed', 10.0, 80, true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO participations (activity_id, user_id, status, created_at)
SELECT p.activity_id, p.user_id, 'accepted', a.starts_at - INTERVAL '6 days'
FROM (VALUES
  ('c0000000-0000-4000-a000-000000000027'::uuid, 'd0000000-0000-4000-a000-000000000002'::uuid),
  ('c0000000-0000-4000-a000-000000000027'::uuid, 'd0000000-0000-4000-a000-000000000008'::uuid),
  ('c0000000-0000-4000-a000-000000000027'::uuid, 'd0000000-0000-4000-a000-000000000007'::uuid),
  ('c0000000-0000-4000-a000-000000000027'::uuid, 'd0000000-0000-4000-a000-000000000003'::uuid),
  ('c0000000-0000-4000-a000-000000000027'::uuid, 'd0000000-0000-4000-a000-000000000006'::uuid)
) AS p(activity_id, user_id)
JOIN activities a ON a.id = p.activity_id
ON CONFLICT (user_id, activity_id) DO NOTHING;

DO $$
BEGIN
  PERFORM set_config('junto.bypass_lock', 'true', true);
  UPDATE participations SET confirmed_present = true
  WHERE activity_id = 'c0000000-0000-4000-a000-000000000027' AND status = 'accepted';
  -- Léa M. skipped it (keeps her reliability in the « Correcte » band).
  UPDATE participations SET confirmed_present = false
  WHERE activity_id = 'c0000000-0000-4000-a000-000000000027'
    AND user_id = 'd0000000-0000-4000-a000-000000000006' AND status = 'accepted';
  PERFORM set_config('junto.bypass_lock', 'false', true);
END $$;

INSERT INTO reputation_votes (voter_id, voted_id, activity_id, badge_key, counted_at, created_at)
SELECT v.voter, v.voted, v.activity, v.badge, a.starts_at + a.duration + INTERVAL '26 hours', a.starts_at + a.duration + INTERVAL '5 hours'
FROM (VALUES
  ('d0000000-0000-4000-a000-000000000002'::uuid, 'd0000000-0000-4000-a000-000000000008'::uuid, 'c0000000-0000-4000-a000-000000000027'::uuid, 'level_over'),
  ('d0000000-0000-4000-a000-000000000007'::uuid, 'd0000000-0000-4000-a000-000000000008'::uuid, 'c0000000-0000-4000-a000-000000000027'::uuid, 'level_over'),
  ('d0000000-0000-4000-a000-000000000003'::uuid, 'd0000000-0000-4000-a000-000000000008'::uuid, 'c0000000-0000-4000-a000-000000000027'::uuid, 'level_over')
) AS v(voter, voted, activity, badge)
JOIN activities a ON a.id = v.activity
ON CONFLICT (voter_id, voted_id, activity_id, badge_key) DO NOTHING;

DO $$
BEGIN
  PERFORM recalculate_reliability_score('d0000000-0000-4000-a000-000000000008');
  PERFORM recalculate_reliability_score('d0000000-0000-4000-a000-000000000006');
  PERFORM recalculate_reliability_score('d0000000-0000-4000-a000-000000000002');
  PERFORM recalculate_reliability_score('d0000000-0000-4000-a000-000000000003');
  PERFORM recalculate_reliability_score('d0000000-0000-4000-a000-000000000007');
END $$;
